In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.DataFrame({                          # DataFrame: it shows data in Tabular form with index
    "Name":["Pawan","Pooja"],
    "Marks":[80,99]
})
print(df)

    Name  Marks
0  Pawan     80
1  Pooja     99

In [3]:
s=pd.Series([10,20,30,40],index=["a","b","c","d"])     #index : means we can use any type of indexing like (1,2,3),(a,b,c)(A,B,C)etc.
                                                      # series: shows data in 1-D 
print(s)

a    10
b    20
c    30
d    40
dtype: int64

In [4]:
# Creating dataframe by dictionary
data={
    "Name":["Pawan","Pooja"],
    "Age":[23,23],
    "Address":["Rajghat","Kalaupur"]
}
df=pd.DataFrame(data)
print(df)

    Name  Age   Address
0  Pawan   23   Rajghat
1  Pooja   23  Kalaupur

In [5]:
# for viewing or feteching data from top(default=5 like feteches top 5 data)
print(df.head(1))

    Name  Age  Address
0  Pawan   23  Rajghat

In [6]:
# for viewing or feteching data from bottom(default=5 like feteches bottom 5 data)
print(df.tail(1))

    Name  Age   Address
1  Pooja   23  Kalaupur

In [7]:
print(df.shape)      # shape : provide or show how many rows and column

(2, 3)

In [8]:
print(df.info())    # info: show all details about data

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     2 non-null      str
 1   Age      2 non-null      int64
 2   Address  2 non-null      str
dtypes: int64(1), str(2)
memory usage: 180.0 bytes
None

In [9]:
#Creating csv directly 
data={
    "std_id":[101,102,103,104],
    "std_name":["Pawan","santosh","naresh","dammer"],
    "Age":[23,22,22,22],
    "Marks":[90,50,60,80]
}
df=pd.DataFrame(data)
df.to_csv("studentrecord.csv",index=False)
print("Created Successfully")

Created Successfully

In [2]:
df=pd.read_csv("salary.csv")
print(df)

    Name Department   Salary   Age
0    Ram         IT  50000.0  25.0
1  Shyam         HR  40000.0  30.0
2   Hari         IT      NaN  28.0
3   Sita    Finance  60000.0   NaN
4   Gita         HR  45000.0  26.0

In [11]:
# to display specific column 
print(df[["Name","Salary"]])

    Name   Salary
0    Ram  50000.0
1  Shyam  40000.0
2   Hari      NaN
3   Sita  60000.0
4   Gita  45000.0

In [12]:
# if NaN occur or exits we can drop or delete that rows from data or table
clean_df=df.dropna()
print(clean_df)

    Name Department   Salary   Age
0    Ram         IT  50000.0  25.0
1  Shyam         HR  40000.0  30.0
4   Gita         HR  45000.0  26.0

In [13]:
# removing only specific NaN like if salary is NaN then removed that row only
print(df.dropna(subset=["Salary"]))

    Name Department   Salary   Age
0    Ram         IT  50000.0  25.0
1  Shyam         HR  40000.0  30.0
3   Sita    Finance  60000.0   NaN
4   Gita         HR  45000.0  26.0

In [14]:
# for removing NaN vaule based on column
print(df.dropna(axis=1))     # axis =1 : means for column and 0 for rows

    Name Department
0    Ram         IT
1  Shyam         HR
2   Hari         IT
3   Sita    Finance
4   Gita         HR

In [15]:
# feteching data using index
print(df["Name"][1])

Shyam

In [16]:
# loc : it returns data based on label

# syntax:     df.loc[row_label,column_label]

print(df.loc[0])

Name              Ram
Department         IT
Salary        50000.0
Age              25.0
Name: 0, dtype: object

In [17]:
# display only specific data like name only
print(df.loc[0,"Name"])

Ram

In [18]:
# displaying like data from 1-3 index
print(df.loc[1:3])    # 3 is inclusive

    Name Department   Salary   Age
1  Shyam         HR  40000.0  30.0
2   Hari         IT      NaN  28.0
3   Sita    Finance  60000.0   NaN

In [19]:
print(df.loc[:,"Name"])     # single column

0      Ram
1    Shyam
2     Hari
3     Sita
4     Gita
Name: Name, dtype: str

In [20]:
# multiple column
print(df.loc[:,["Name","Age"]])      # ' : ' means display all rows

    Name   Age
0    Ram  25.0
1  Shyam  30.0
2   Hari  28.0
3   Sita   NaN
4   Gita  26.0

In [21]:
# iloc : return data based on index

# suntax : df.iloc[row_index,column_index]

print(df.iloc[0])

Name              Ram
Department         IT
Salary        50000.0
Age              25.0
Name: 0, dtype: object

In [22]:
print(df.iloc[0,1])

IT

In [23]:
# displaying like data from 1-3 index
print(df.iloc[1:3])     # 3 is exclusive

    Name Department   Salary   Age
1  Shyam         HR  40000.0  30.0
2   Hari         IT      NaN  28.0

In [24]:
print(df.iloc[:,2])   # : means all rows and 2 means index 2 from column

0    50000.0
1    40000.0
2        NaN
3    60000.0
4    45000.0
Name: Salary, dtype: float64

In [25]:
# Difference between loc and iloc

  # loc : uses labels , end index inclusive 
  # iloc : uses possitions , end index exclusive

In [26]:
print(df.loc[df["Salary"]>45000])   # checking single condition

   Name Department   Salary   Age
0   Ram         IT  50000.0  25.0
3  Sita    Finance  60000.0   NaN

In [27]:
print(df.loc[(df["Salary"]>45000) & (df["Age"]<30)])     # multiple conditions

  Name Department   Salary   Age
0  Ram         IT  50000.0  25.0

In [28]:
# increasing salary

df.loc[df["Department"]=="IT","Salary"]+=5000
print(df)

    Name Department   Salary   Age
0    Ram         IT  55000.0  25.0
1  Shyam         HR  40000.0  30.0
2   Hari         IT      NaN  28.0
3   Sita    Finance  60000.0   NaN
4   Gita         HR  45000.0  26.0

In [29]:
# update values

df.loc[df["Age"]>25,"Department"]="Senoir"
print(df)

    Name Department   Salary   Age
0    Ram         IT  55000.0  25.0
1  Shyam     Senoir  40000.0  30.0
2   Hari     Senoir      NaN  28.0
3   Sita    Finance  60000.0   NaN
4   Gita     Senoir  45000.0  26.0

In [30]:
# Adding column using loc[]

df.loc[:,"Bonus"]=df["Salary"]*0.1
print(df)

    Name Department   Salary   Age   Bonus
0    Ram         IT  55000.0  25.0  5500.0
1  Shyam     Senoir  40000.0  30.0  4000.0
2   Hari     Senoir      NaN  28.0     NaN
3   Sita    Finance  60000.0   NaN  6000.0
4   Gita     Senoir  45000.0  26.0  4500.0

#Assignment

In [31]:
#select only salary col using loc

print(df.loc[:,["Salary"]])

    Salary
0  55000.0
1  40000.0
2      NaN
3  60000.0
4  45000.0

In [32]:
#select name and salary col using loc

print(df.loc[:,["Name","Salary"]])

    Name   Salary
0    Ram  55000.0
1  Shyam  40000.0
2   Hari      NaN
3   Sita  60000.0
4   Gita  45000.0

In [33]:
# select first 2 col using iloc

print(df.iloc[:,1:3])

  Department   Salary
0         IT  55000.0
1     Senoir  40000.0
2     Senoir      NaN
3    Finance  60000.0
4     Senoir  45000.0

In [34]:
# select all rows and col using loc

print(df.loc[:,:])

    Name Department   Salary   Age   Bonus
0    Ram         IT  55000.0  25.0  5500.0
1  Shyam     Senoir  40000.0  30.0  4000.0
2   Hari     Senoir      NaN  28.0     NaN
3   Sita    Finance  60000.0   NaN  6000.0
4   Gita     Senoir  45000.0  26.0  4500.0

In [35]:
# select dept and age using iloc

print(df.iloc[:,[1,3]])

  Department   Age
0         IT  25.0
1     Senoir  30.0
2     Senoir  28.0
3    Finance   NaN
4     Senoir  26.0

In [36]:
# select 1st row and all col using loc

print(df.loc[0,:])

Name              Ram
Department         IT
Salary        55000.0
Age              25.0
Bonus          5500.0
Name: 0, dtype: object

In [37]:
# select rows: 1 to 3 and col: Name,Salary using loc

print(df.loc[1:3,["Name","Salary"]])

    Name   Salary
1  Shyam  40000.0
2   Hari      NaN
3   Sita  60000.0

In [38]:
# select first 3 rows and first 2 col using iloc

print(df.iloc[0:3,[0,1]])

    Name Department
0    Ram         IT
1  Shyam     Senoir
2   Hari     Senoir

In [39]:
# select salary>45000, show name and salary

print(df.loc[df["Salary"]>45000 , ["Name","Salary"]])

   Name   Salary
0   Ram  55000.0
3  Sita  60000.0

In [40]:
# select last col using iloc

print(df.iloc[:,-1])

0    5500.0
1    4000.0
2       NaN
3    6000.0
4    4500.0
Name: Bonus, dtype: float64

In [41]:
# select col in reverse order

print(df.iloc[:,::-1])           # ::-1 is used to reverse order

    Bonus   Age   Salary Department   Name
0  5500.0  25.0  55000.0         IT    Ram
1  4000.0  30.0  40000.0     Senoir  Shyam
2     NaN  28.0      NaN     Senoir   Hari
3  6000.0   NaN  60000.0    Finance   Sita
4  4500.0  26.0  45000.0     Senoir   Gita

In [42]:
# select all col except age

df = df.drop(columns=['Age'])   # Method 1: Using drop()
print(df)

df = df[[col for col in df.columns if col != 'Age']]    # Method 2: Using column selection
print(df)

df = df.loc[:, df.columns != 'Age']   # Method 3: Using loc
print(df)

    Name Department   Salary   Bonus
0    Ram         IT  55000.0  5500.0
1  Shyam     Senoir  40000.0  4000.0
2   Hari     Senoir      NaN     NaN
3   Sita    Finance  60000.0  6000.0
4   Gita     Senoir  45000.0  4500.0
    Name Department   Salary   Bonus
0    Ram         IT  55000.0  5500.0
1  Shyam     Senoir  40000.0  4000.0
2   Hari     Senoir      NaN     NaN
3   Sita    Finance  60000.0  6000.0
4   Gita     Senoir  45000.0  4500.0
    Name Department   Salary   Bonus
0    Ram         IT  55000.0  5500.0
1  Shyam     Senoir  40000.0  4000.0
2   Hari     Senoir      NaN     NaN
3   Sita    Finance  60000.0  6000.0
4   Gita     Senoir  45000.0  4500.0

In [45]:
print(df)

    Name Department   Salary   Bonus
0    Ram         IT  55000.0  5500.0
1  Shyam     Senoir  40000.0  4000.0
2   Hari     Senoir      NaN     NaN
3   Sita    Finance  60000.0  6000.0
4   Gita     Senoir  45000.0  4500.0

In [46]:
# fillna : replace NaN with other vaule

df["Salary"]=df["Salary"].fillna(0)
print(df)

    Name Department   Salary   Bonus
0    Ram         IT  55000.0  5500.0
1  Shyam     Senoir  40000.0  4000.0
2   Hari     Senoir      0.0     NaN
3   Sita    Finance  60000.0  6000.0
4   Gita     Senoir  45000.0  4500.0

In [49]:
# filling mean value at NaN 

df["Salary"]=df["Salary"].fillna(df["Salary"].mean())
print(df)

    Name Department   Salary   Bonus
0    Ram         IT  55000.0  5500.0
1  Shyam     Senoir  40000.0  4000.0
2   Hari     Senoir      0.0     NaN
3   Sita    Finance  60000.0  6000.0
4   Gita     Senoir  45000.0  4500.0

In [48]:
# sorting on the basis of column

print(df.sort_values(by="Salary"))     # ascending order

    Name Department   Salary   Bonus
2   Hari     Senoir      0.0     NaN
1  Shyam     Senoir  40000.0  4000.0
4   Gita     Senoir  45000.0  4500.0
0    Ram         IT  55000.0  5500.0
3   Sita    Finance  60000.0  6000.0

In [52]:
print(df.sort_values(by="Salary",ascending=False))  # decending order

    Name Department   Salary   Bonus
3   Sita    Finance  60000.0  6000.0
0    Ram         IT  55000.0  5500.0
4   Gita     Senoir  45000.0  4500.0
1  Shyam     Senoir  40000.0  4000.0
2   Hari     Senoir      0.0     NaN

In [55]:
print(df.sort_values(by=["Department","Salary"]))   # sorting multiple column

# first sort by department
# then sort Salary within each department

    Name Department   Salary   Bonus
3   Sita    Finance  60000.0  6000.0
0    Ram         IT  55000.0  5500.0
2   Hari     Senoir      0.0     NaN
1  Shyam     Senoir  40000.0  4000.0
4   Gita     Senoir  45000.0  4500.0

In [54]:
# counts frequency of values in a column

print(df["Department"].value_counts())

Department
Senoir     3
IT         1
Finance    1
Name: count, dtype: int64

In [56]:
print(df["Department"].value_counts(normalize=True))

Department
Senoir     0.6
IT         0.2
Finance    0.2
Name: proportion, dtype: float64

In [57]:
# changing into percentage

df["HighSalary"]=df["Salary"]>45000
print(df["HighSalary"].value_counts(normalize=True)*100)

HighSalary
False    60.0
True     40.0
Name: proportion, dtype: float64

In [58]:
# unique: it return unique values like return values after removing duplicate vaule

print(df["Department"].unique())

<StringArray>
['IT', 'Senoir', 'Finance']
Length: 3, dtype: str

In [59]:
print(df["Department"].nunique())   # nunique return number of unique value

3

In [60]:
print(df["Salary"].unique())

[55000. 40000.     0. 60000. 45000.]

In [62]:
print(df)

    Name Department   Salary   Age
0    Ram         IT  50000.0  25.0
1  Shyam         HR  40000.0  30.0
2   Hari         IT      NaN  28.0
3   Sita    Finance  60000.0   NaN
4   Gita         HR  45000.0  26.0

In [63]:
df=pd.read_csv("dataset.csv")
print(df)

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112       NaN
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45         NaN    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60    20201226    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132       NaN
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

In [72]:
df['Data']=pd.to_datetime(df['Date'],format='mixed')
print(df.to_string())

    Duration        Date  Pulse  Maxpulse  Calories       Data
0         60  2020/12/01    110       130     409.1 2020-12-01
1         60  2020/12/02    117       145     479.0 2020-12-02
2         60  2020/12/03    103       135     340.0 2020-12-03
3         45  2020/12/04    109       175     282.4 2020-12-04
4         45  2020/12/05    117       148     406.0 2020-12-05
5         60  2020/12/06    102       127     300.0 2020-12-06
6         60  2020/12/07    110       136     374.0 2020-12-07
7         45  2020/12/08    104       134     253.3 2020-12-08
8         30  2020/12/09    109       133     195.1 2020-12-09
9         60  2020/12/10     98       124     269.0 2020-12-10
10        60  2020/12/11    103       147     329.3 2020-12-11
11        60  2020/12/12    100       120     250.7 2020-12-12
12        60  2020/12/12    100       120     250.7 2020-12-12
13        60  2020/12/13    106       128     345.3 2020-12-13
14        60  2020/12/14    104       132     379.3 2020-12-14
15        60  2020/12/15     98       123     275.0 2020-12-15
16        60  2020/12/16     98       120     215.2 2020-12-16
17        60  2020/12/17    100       120     300.0 2020-12-17
18        45  2020/12/18     90       112       NaN 2020-12-18
19        60  2020/12/19    103       123     323.0 2020-12-19
20        45  2020/12/20     97       125     243.0 2020-12-20
21        60  2020/12/21    108       131     364.2 2020-12-21
22        45         NaN    100       119     282.0        NaT
23        60  2020/12/23    130       101     300.0 2020-12-23
24        45  2020/12/24    105       132     246.0 2020-12-24
25        60  2020/12/25    102       126     334.5 2020-12-25
26        60    20201226    100       120     250.0 2020-12-26
27        60  2020/12/27     92       118     241.0 2020-12-27
28        60  2020/12/28    103       132       NaN 2020-12-28
29        60  2020/12/29    100       132     280.0 2020-12-29
30        60  2020/12/30    102       129     380.3 2020-12-30
31        60  2020/12/31     92       115     243.0 2020-12-31

In [66]:
df.loc[7,"Duration"]=45     # data cleaning like changing data or replace data 
print(df)

    Duration        Date  Pulse  Maxpulse  Calories       Data
0         60  2020/12/01    110       130     409.1 2020-12-01
1         60  2020/12/02    117       145     479.0 2020-12-02
2         60  2020/12/03    103       135     340.0 2020-12-03
3         45  2020/12/04    109       175     282.4 2020-12-04
4         45  2020/12/05    117       148     406.0 2020-12-05
5         60  2020/12/06    102       127     300.0 2020-12-06
6         60  2020/12/07    110       136     374.0 2020-12-07
7         45  2020/12/08    104       134     253.3 2020-12-08
8         30  2020/12/09    109       133     195.1 2020-12-09
9         60  2020/12/10     98       124     269.0 2020-12-10
10        60  2020/12/11    103       147     329.3 2020-12-11
11        60  2020/12/12    100       120     250.7 2020-12-12
12        60  2020/12/12    100       120     250.7 2020-12-12
13        60  2020/12/13    106       128     345.3 2020-12-13
14        60  2020/12/14    104       132     379.3 2020-12-14
15        60  2020/12/15     98       123     275.0 2020-12-15
16        60  2020/12/16     98       120     215.2 2020-12-16
17        60  2020/12/17    100       120     300.0 2020-12-17
18        45  2020/12/18     90       112       NaN 2020-12-18
19        60  2020/12/19    103       123     323.0 2020-12-19
20        45  2020/12/20     97       125     243.0 2020-12-20
21        60  2020/12/21    108       131     364.2 2020-12-21
22        45         NaN    100       119     282.0        NaT
23        60  2020/12/23    130       101     300.0 2020-12-23
24        45  2020/12/24    105       132     246.0 2020-12-24
25        60  2020/12/25    102       126     334.5 2020-12-25
26        60    20201226    100       120     250.0 2020-12-26
27        60  2020/12/27     92       118     241.0 2020-12-27
28        60  2020/12/28    103       132       NaN 2020-12-28
29        60  2020/12/29    100       132     280.0 2020-12-29
30        60  2020/12/30    102       129     380.3 2020-12-30
31        60  2020/12/31     92       115     243.0 2020-12-31

In [69]:
# to remove duplicate row

print(df.duplicated())   # it check whether data is duplicate or not
print(df.drop_duplicates())   # it drop duplicate data

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
dtype: bool
    Duration        Date  Pulse  Maxpulse  Calories       Data
0         60  2020/12/01    110       130     409.1 2020-12-01
1         60  2020/12/02    117       145     479.0 2020-12-02
2         60  2020/12/03    103       135     340.0 2020-12-03
3         45  2020/12/04    109       175     282.4 2020-12-04
4         45  2020/12/05    117       148     406.0 2020-12-05
5         60  2020/12/06    102       127     300.0 2020-12-06
6         60  2020/12/07    110       136     374.0 2020-12-07
7         45  2020/12/08    104       134     253.3 2020-12-08
8         30  2020/12/09    109       133     195.1 2020-12-09
9         60  2020/12/10     98       124     269.0 2020-12-10
10        60  2020/12/11    103       147     329.3 2020-12-11
11        60  2020/12/12    100       120     250.7 2020-12-12
13        60  2020/12/13    106       128     345.3 2020-12-13
14        60  2020/12/14    104       132     379.3 2020-12-14
15        60  2020/12/15     98       123     275.0 2020-12-15
16        60  2020/12/16     98       120     215.2 2020-12-16
17        60  2020/12/17    100       120     300.0 2020-12-17
18        45  2020/12/18     90       112       NaN 2020-12-18
19        60  2020/12/19    103       123     323.0 2020-12-19
20        45  2020/12/20     97       125     243.0 2020-12-20
21        60  2020/12/21    108       131     364.2 2020-12-21
22        45         NaN    100       119     282.0        NaT
23        60  2020/12/23    130       101     300.0 2020-12-23
24        45  2020/12/24    105       132     246.0 2020-12-24
25        60  2020/12/25    102       126     334.5 2020-12-25
26        60    20201226    100       120     250.0 2020-12-26
27        60  2020/12/27     92       118     241.0 2020-12-27
28        60  2020/12/28    103       132       NaN 2020-12-28
29        60  2020/12/29    100       132     280.0 2020-12-29
30        60  2020/12/30    102       129     380.3 2020-12-30
31        60  2020/12/31     92       115     243.0 2020-12-31

In [73]:
# correlation: it shows relationship between tables
# correlation (0-1)

df.corr()

ValueError: could not convert string to float: '2020/12/01'

In [3]:
print(df)

    Name Department   Salary   Age
0    Ram         IT  50000.0  25.0
1  Shyam         HR  40000.0  30.0
2   Hari         IT      NaN  28.0
3   Sita    Finance  60000.0   NaN
4   Gita         HR  45000.0  26.0

In [4]:
df=pd.DataFrame({
    "Name":["Pawan","Santosh","Naresh","Dammer","Nirmal","Pradeep"],
    "Dept":["IT","HR","IT","Finance","HR","IT"],
    "Salary":["50000","40000","60000","45000","70000","45000"],
    "Age":["23","24","25","32","29","26"]
})
print(df)

      Name     Dept Salary Age
0    Pawan       IT  50000  23
1  Santosh       HR  40000  24
2   Naresh       IT  60000  25
3   Dammer  Finance  45000  32
4   Nirmal       HR  70000  29
5  Pradeep       IT  45000  26

In [5]:
# groupby : split on the basis of column

df.groupby("Dept")

In [6]:
for dept,data in df.groupby("Dept"):   # for loop in groupby method 
    print(dept)
    print(data)

Finance
     Name     Dept Salary Age
3  Dammer  Finance  45000  32
HR
      Name Dept Salary Age
1  Santosh   HR  40000  24
4   Nirmal   HR  70000  29
IT
      Name Dept Salary Age
0    Pawan   IT  50000  23
2   Naresh   IT  60000  25
5  Pradeep   IT  45000  26

In [15]:
print(df.dtypes)

Name        str
Dept        str
Salary    int64
Age       int64
dtype: object

In [17]:
df["Salary"] = df["Salary"].astype(int)   # changing into int 
df["Age"] = df["Age"].astype(int)         # changing into int
print(df)
print(df.dtypes)                     # checking data type

      Name     Dept  Salary  Age
0    Pawan       IT   50000   23
1  Santosh       HR   40000   24
2   Naresh       IT   60000   25
3   Dammer  Finance   45000   32
4   Nirmal       HR   70000   29
5  Pradeep       IT   45000   26
Name        str
Dept        str
Salary    int64
Age       int64
dtype: object

In [18]:
df.groupby("Dept")["Salary"].mean()

Dept
Finance    45000.000000
HR         55000.000000
IT         51666.666667
Name: Salary, dtype: float64

In [19]:
df.groupby("Dept")["Salary"].sum()

Dept
Finance     45000
HR         110000
IT         155000
Name: Salary, dtype: int64

In [10]:
df.groupby("Dept")["Salary"].max()

Dept
Finance    45000
HR         70000
IT         60000
Name: Salary, dtype: str

In [20]:
df.groupby("Dept")["Salary"].agg(["mean","sum","max","min"])

                 mean     sum    max    min
Dept
Finance  45000.000000   45000  45000  45000
HR       55000.000000  110000  70000  40000
IT       51666.666667  155000  60000  45000

In [21]:
df.groupby("Dept").agg({
    "Salary":["mean","max"],
    "Age":["min","max"]
})

               Salary        Age
                 mean    max min max
Dept
Finance  45000.000000  45000  32  32
HR       55000.000000  70000  24  29
IT       51666.666667  60000  23  26

In [22]:
df.groupby(["Dept","Age"])["Salary"].mean()

Dept     Age
Finance  32     45000.0
HR       24     40000.0
         29     70000.0
IT       23     50000.0
         25     60000.0
         26     45000.0
Name: Salary, dtype: float64

In [23]:
df.groupby("Dept")["Name"].count()   # count name of dept

Dept
Finance    1
HR         2
IT         3
Name: Name, dtype: int64

In [24]:
df.groupby("Dept").filter(lambda x : x["Salary"].mean()>45000)

      Name Dept  Salary  Age
0    Pawan   IT   50000   23
1  Santosh   HR   40000   24
2   Naresh   IT   60000   25
4   Nirmal   HR   70000   29
5  Pradeep   IT   45000   26

In [25]:
df.groupby("Dept")["Salary"].mean().sort_values()

Dept
Finance    45000.000000
IT         51666.666667
HR         55000.000000
Name: Salary, dtype: float64

In [26]:
df.groupby("Dept")["Salary"].mean().sort_values(ascending=False)

Dept
HR         55000.000000
IT         51666.666667
Finance    45000.000000
Name: Salary, dtype: float64

In [27]:
# describe calculate all aggregation operation , it ignore NaN

print(df.describe())

             Salary        Age
count      6.000000   6.000000
mean   51666.666667  26.500000
std    11254.628677   3.391165
min    40000.000000  23.000000
25%    45000.000000  24.250000
50%    47500.000000  25.500000
75%    57500.000000  28.250000
max    70000.000000  32.000000